#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2025 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.3.4
# Product:       sfm3505
# Model-Version: 1.1.0
#

import argparse
import time
from sensirion_i2c_driver import LinuxI2cTransceiver, I2cConnection, CrcCalculator
from sensirion_driver_adapters.i2c_adapter.i2c_channel import I2cChannel
from sensirion_i2c_sfm3505.device import Sfm3505Device

parser = argparse.ArgumentParser()
parser.add_argument('--i2c-port', '-p', default='/dev/i2c-1')
args = parser.parse_args()

with LinuxI2cTransceiver(args.i2c_port) as i2c_transceiver:
    channel = I2cChannel(I2cConnection(i2c_transceiver),
                         slave_address=0x2E,
                         crc=CrcCalculator(8, 0x31, 0xff, 0x0))
    sensor = Sfm3505Device(channel)
    try:
        sensor.stop_continuous_measurement()
        time.sleep(0.1)
    except BaseException:
        ...
    (product_identifier, serial_number
     ) = sensor.read_product_identifier()
    print(f"product_identifier: {product_identifier}; "
          f"serial_number: {serial_number}; "
          )
    sensor.start_continuous_measurement()
    for i in range(100):
        try:
            time.sleep(0.005)
            (a_air_flow, a_o2_flow
             ) = sensor.read_all_measurement_data()
            print(f"a_air_flow: {a_air_flow}; "
                  f"a_o2_flow: {a_o2_flow}; "
                  )
        except BaseException:
            continue
    sensor.stop_continuous_measurement()
